### ISSUE TITLE
Error: Resolves to an APK archive which is not supported as a compilation dependency

### ISSUE THREAD

**Issue by ziyaddin** [cooltechworks/BitmapMerger#4]
Hello, I encounter a compilation error, when I try to compile library in my app. I have already included Jitpack url and compile package. How can I solve this problem?

**Comment by sharish** [comment]
This repo does not have a release there not compatible with jitpack. The repo was not made like a library project thereby no releases are present. You can copy the source and add it in your own project for now.

**Comment by ziyaddin** [comment]
Thanks for explanation @sharish.
